(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const r of t.addedNodes)r.tagName==="LINK"&&r.rel==="modulepreload"&&s(r)}).observe(document,{childList:!0,subtree:!0});function c(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=c(e);fetch(e.href,t)}})();const M="https://app.ticketmaster.com/discovery/v2/events.json",j="SD3dPZKqy7tpTs7VjSSru5mwqnGlbhOg";async function S(n=0,o="",c=""){var r;let s=`${M}?apikey=${j}&page=${n}&size=20`;o&&(s+=`&keyword=${o}`),c&&(s+=`&countryCode=${c}`);const t=await(await fetch(s)).json();return{events:((r=t._embedded)==null?void 0:r.events)||[],totalPages:t.page.totalPages,currentPage:t.page.number}}const k="/js-second-semestr-pr/assets/place-58203bd5.svg",m=document.querySelector(".header__select");function O(n=[]){const o=n.map(({_embedded:e})=>{var t,r,a,l,u,d;return{name:(a=(r=(t=e==null?void 0:e.venues)==null?void 0:t[0])==null?void 0:r.country)==null?void 0:a.name,code:(d=(u=(l=e==null?void 0:e.venues)==null?void 0:l[0])==null?void 0:u.country)==null?void 0:d.countryCode}}),c=Array.from(new Map(o.map(e=>[e.code,e])).values()),s=c.map(e=>`<option value="${e.code}">${e.name}</option>`).join("");return m.insertAdjacentHTML("beforeend",s),c}const q=document.querySelector(".events_collections"),p=document.querySelector(".pag_numbers"),i=document.querySelector(".backdrop"),b=document.querySelector(".modal-close"),E=document.querySelector(".header__input"),I=document.querySelector(".event-logo"),T=document.querySelector(".modal-big-logo");let v="",C="";const g={totalPages:0,currentPage:0};async function f(n=0){const{events:o,totalPages:c,currentPage:s}=await S(n,v,C);g.currentPage=s,g.totalPages=Math.min(c,50),A(o),K()}function A(n=[]){const c=n.filter(s=>s.name.toLowerCase().includes(v.toLowerCase())).map(({images:s,name:e,dates:t,_embedded:r})=>{var L,h,P,w,$;const a=(L=r==null?void 0:r.venues)==null?void 0:L[0];a==null||a.country;const l=((h=a==null?void 0:a.city)==null?void 0:h.name)||"",u=((P=a==null?void 0:a.address)==null?void 0:P.line1)||"",d=`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(u+" "+l)}`,y=((w=s==null?void 0:s[0])==null?void 0:w.url)||"./img/no-image.jpg";return`
        <li class="events_item fade-in is-visible" data-img="${y}">
            <div class="overflow"></div>
            <img class="events_img" src="${y}" alt="${e}" />
            <h3 class="events_title">${e}</h3>
            <p class="events__date">${(($=t==null?void 0:t.start)==null?void 0:$.localDate)||""}</p>
            <div class="event-box">
                <img class="modal-place" src="${k}" alt="place">
                <a class="event__link" href="${d}" target="_blank">${l}</a>
            </div>       
        </li>`}).join("");q.innerHTML=c}function K(){const{currentPage:n,totalPages:o}=g;p.innerHTML="";const c=t=>{const r=document.createElement("button");r.textContent=t+1,r.classList.add("page"),t===n&&r.classList.add("active"),r.addEventListener("click",()=>{f(t)}),p.appendChild(r)},s=Math.max(0,n-2),e=Math.min(o-1,n+2);s>0&&(c(0),p.append("..."));for(let t=s;t<=e;t++)c(t);e<o-1&&(p.append("..."),c(o-1))}function R(n){I.src=n,T.src=n}q.addEventListener("click",n=>{const o=n.target.closest(".events_item");if(!o)return;const c=o.dataset.img;R(c),i.classList.add("is-open")});i.addEventListener("click",n=>{n.target===i&&i.classList.remove("is-open")});window.addEventListener("keydown",n=>{n.code==="Escape"&&i.classList.remove("is-open")});b.addEventListener("click",()=>{i.classList.remove("is-open")});function _(n,o=400){let c;return(...s)=>{clearTimeout(c),c=setTimeout(()=>{n(...s)},o)}}const x=_(()=>{v=E.value.trim(),f(0)},400);E.addEventListener("input",x);f(0);async function B(){const{events:n}=await S(),o=O(n);console.log(o)}B();m.addEventListener("change",()=>{C=m.value,f(0)});
//# sourceMappingURL=commonHelpers.js.map
