(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))r(t);new MutationObserver(t=>{for(const e of t)if(e.type==="childList")for(const c of e.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&r(c)}).observe(document,{childList:!0,subtree:!0});function n(t){const e={};return t.integrity&&(e.integrity=t.integrity),t.referrerPolicy&&(e.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?e.credentials="include":t.crossOrigin==="anonymous"?e.credentials="omit":e.credentials="same-origin",e}function r(t){if(t.ep)return;t.ep=!0;const e=n(t);fetch(t.href,e)}})();const E="https://app.ticketmaster.com/discovery/v2/events.json",w="SD3dPZKqy7tpTs7VjSSru5mwqnGlbhOg";async function b(s=0){var r;const n=await(await fetch(`${E}?apikey=${w}&page=${s}&size=20`)).json();return{events:((r=n._embedded)==null?void 0:r.events)||[],totalPages:n.page.totalPages,currentPage:n.page.number}}const y=document.querySelector(".events_collections"),i=document.querySelector(".pag_numbers"),q=document.querySelectorAll(".fade-in"),a=document.querySelector(".backdrop"),S=document.querySelector(".modal-close"),$=document.querySelector(".event-logo"),_=document.querySelector(".modal-big-logo");async function L(s=0){const{events:o,totalPages:n,currentPage:r}=await b(s);l.currentPage=r,l.totalPages=Math.min(n,50),M(o),O(),console.log("Events from API:",o)}function M(s=[]){const o=s.map(({images:n,name:r,dates:t,_embedded:e})=>{var m,p,f,g,v;const c=(m=e==null?void 0:e.venues)==null?void 0:m[0],d=((p=c==null?void 0:c.city)==null?void 0:p.name)||"",h=((f=c==null?void 0:c.address)==null?void 0:f.line1)||"",P=`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(h+" "+d)}`,u=((g=n==null?void 0:n[0])==null?void 0:g.url)||"./img/no-image.jpg";return`
        <li class="events_item fade-in is-visible" data-img="${u}">
            <div class="overflow"></div>
            <img class="events_img" src="${u}" alt="${r}" />
            <h3 class="events_title">${r}</h3>
            <p class="events__date">${((v=t==null?void 0:t.start)==null?void 0:v.localDate)||""}</p>
            <div class="event-box">
                <img class="modal-place" src="../img/place.svg" alt="place">
                <a class="event__link" href="${P}">${d}</a>
            </div>       
        </li>`}).join("");y.innerHTML=o}const l={totalPages:0,currentPage:0};function O(){const{currentPage:s,totalPages:o}=l;i.innerHTML="";const n=e=>{const c=document.createElement("button");c.textContent=e+1,c.classList.add("page"),e===s&&c.classList.add("active"),c.addEventListener("click",()=>{L(e)}),i.appendChild(c)},r=Math.max(0,s-2),t=Math.min(o-1,s+2);r>0&&(n(0),i.appendChild(document.createTextNode("...")));for(let e=r;e<=t;e+=1)n(e);t<o-1&&(i.append("..."),n(o-1))}L(0);q.forEach((s,o)=>{setTimeout(()=>{s.classList.add("is-visible")},o*60)});function k(s){$.src=s,_.src=s}y.addEventListener("click",s=>{const o=s.target.closest(".events_item");if(!o)return;const n=o.dataset.img;k(n),a.classList.add("is-open")});a.addEventListener("click",s=>{s.target===a&&a.classList.remove("is-open")});window.addEventListener("keydown",j);function j(s){s.code==="Escape"&&a.classList.remove("is-open")}S.addEventListener("click",()=>{a.classList.remove("is-open")});
//# sourceMappingURL=commonHelpers.js.map
